--카메라 DB 
CREATE TABLE CAMERA(
CAMERA_NUM NUMBER(5) PRIMARY KEY,
CAMERA_STORENAME VARCHAR2(50) ,
CAMERA_TOTAL NUMBER(7) ,
CAMERA_DATE DATE ,
USER_ID VARCHAR2(15) ,
ORIGINAL_FILEPATH	VARCHAR2(100),
RENAME_FILEPATH	VARCHAR2(100),
CONSTRAINT FK_USER FOREIGN KEY(USER_ID) REFERENCES MEMBER(USERID)
);

CREATE TABLE PRODUCT(
PRODUCT_NO NUMBER(7) PRIMARY KEY,
CAMERA_NUM NUMBER(5) NOT NULL,
CONSTRAINT FK_CAMERA FOREIGN KEY(CAMERA_NUM) REFERENCES CAMERA(CAMERA_NUM),
PRODUCT_NAME VARCHAR2(150),
PRODUCT_COUNT NUMBER(4) ,
UNIT_PRICE NUMBER(7) ,
PRODUCT_PRICE NUMBER(8)

);

drop table product;
drop table camera;
drop table calboard;
drop table accountbook;
----
drop sequence seq;
drop sequence seq_cid;
drop sequence seq_pid;
drop sequence CALBOARD_SEQ;
--
--
delete from camera where camera_num = 65;


select* from product;
select* from camera;
select* from calboard;
select* from accountbook;

CREATE SEQUENCE seq
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 10000
NOCYCLE
NOCACHE
ORDER ;

CREATE SEQUENCE SEQ_CID
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 10000
NOCYCLE
NOCACHE
NOORDER;

CREATE SEQUENCE SEQ_PID
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 10000
NOCYCLE
NOCACHE
NOORDER;

-- camera_num 이 64가 될떄까지 임시데이터 만들어줘야함. 8 번 실행
INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 40000, '2022-04-08', 'user01' );
INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 30000, '2022-04-09', 'user01' );
INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 50000, '2022-04-10', 'user01' );
INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 60000, '2022-04-11', 'user01' );
INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 70000, '2022-04-12', 'user01' );
INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 80000, '2022-04-13', 'user01' );
INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 90000, sysdate, 'user01' );
INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 100000, '2022-04-06', 'user01' );

INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 1300000, '2022-03-03', 'user01' );
INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 6300000, '2022-03-06', 'user01' );
INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 5300000, '2022-03-05', 'user01' );
INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 4300000, '2022-03-04', 'user01' );


INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 1300000, '2022-03-20', 'user01' );
INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 1300000, '2022-03-21', 'user01' );
INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 3300000, '2022-03-22', 'user01' );
INSERT INTO CAMERA(CAMERA_NUM,CAMERA_STORENAME,CAMERA_TOTAL,CAMERA_DATE, USER_ID)
VALUES(SEQ_CID.nextval, 'emart24', 3300000, '2022-03-23', 'user01' );

INSERT INTO PRODUCT(PRODUCT_NO, CAMERA_NUM, PRODUCT_NAME, PRODUCT_COUNT, UNIT_PRICE, PRODUCT_PRICE)
VALUES(SEQ_PID.nextval, 6, '씨그램', 2, 500, 1000 );
INSERT INTO PRODUCT(PRODUCT_NO, CAMERA_NUM, PRODUCT_NAME, PRODUCT_COUNT, UNIT_PRICE, PRODUCT_PRICE)
VALUES(SEQ_PID.nextval, 6, '새콤달콤', 1, 500, 500 );

commit;

--카메라 DB 끝


-- CALENDER DB 
CREATE TABLE "CALBOARD"
    (   "SEQ" NUMBER NOT NULL ENABLE,
        "ID" VARCHAR2(20) NOT NULL ENABLE,
        "TITLE" VARCHAR2(1000) NOT NULL ENABLE,
        "CONTENT" VARCHAR2(4000) NOT NULL ENABLE,
        "MDATE" VARCHAR2(12) NOT NULL ENABLE,
        "REGDATE" DATE NOT NULL ENABLE,
        CONSTRAINT "CALBOARD_PK" PRIMARY KEY ("SEQ")
    );
    
CREATE SEQUENCE CALBOARD_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 10000
NOCYCLE
NOCACHE
NOORDER;

INSERT INTO CALBOARD
VALUES(CALBOARD_SEQ.NEXTVAL, 'K001', '일정제목1', '일정내용1', '202203201420', SYSDATE);

INSERT INTO CALBOARD
VALUES(CALBOARD_SEQ.NEXTVAL, 'K001', '일정제목2', '일정내용2', '202203211620', SYSDATE);

INSERT INTO CALBOARD
VALUES(CALBOARD_SEQ.NEXTVAL, 'K001', '일정제목3', '일정내용3', '202203221520', SYSDATE);

INSERT INTO CALBOARD
VALUES(CALBOARD_SEQ.NEXTVAL, 'K001', '일정제목4', '일정내용4', '202203231820', SYSDATE);

INSERT INTO CALBOARD
VALUES(CALBOARD_SEQ.NEXTVAL, 'K001', '일정제목5', '일정내용5', '202203231920', SYSDATE);


INSERT INTO CALBOARD
VALUES(CALBOARD_SEQ.NEXTVAL, 'K001', '일정제목2', '일정내용2', '202203251620', SYSDATE);

INSERT INTO CALBOARD
VALUES(CALBOARD_SEQ.NEXTVAL, 'K001', '일정제목3', '일정내용3', '202203225520', SYSDATE);

INSERT INTO CALBOARD
VALUES(CALBOARD_SEQ.NEXTVAL, 'K001', '일정제목4', '일정내용4', '202203235820', SYSDATE);

INSERT INTO CALBOARD
VALUES(CALBOARD_SEQ.NEXTVAL, 'K001', '일정제목5', '일정내용5', '202203250120', SYSDATE);


INSERT INTO CALBOARD
VALUES(CALBOARD_SEQ.NEXTVAL, 'user02', '편의점1', '35000원', '202204011120', SYSDATE);

INSERT INTO CALBOARD
VALUES(CALBOARD_SEQ.NEXTVAL, 'user03', '편의점2', '15000원', '202204021220', SYSDATE);

INSERT INTO CALBOARD
VALUES(CALBOARD_SEQ.NEXTVAL, 'user01', '편의점3', '55000원', '202204031620', SYSDATE);

INSERT INTO CALBOARD
VALUES(CALBOARD_SEQ.NEXTVAL, 'admin', '편의점4', '34000원', '202204042220', SYSDATE);
COMMIT;

alter table CALBOARD add constraint CALBOARD_PK primary key(SEQ);  --SEQ를기본키로

ALTER TABLE CALBOARD ADD CONSTRAINT FK_CALWRITER foreign KEY(id) references MEMBER (USERID);  --외래키적용
-- CALENDER DB 끝

--ACCOUNT BOOK DB
CREATE TABLE ACCOUNTBOOK(
    ACCOUNT_NUM INT CONSTRAINT PK_ACCOUNT_NUM PRIMARY KEY,
    ACCOUNTBOOKWRITER VARCHAR2(20) NOT NULL,
    CAMERA_NUM NUMBER(5) NOT NULL,
    CONSTRAINT FK2_CAMERA FOREIGN KEY(CAMERA_NUM) REFERENCES CAMERA(CAMERA_NUM),
    CAMEARA_TOTAL1 INT NOT NULL,
    CAMEARA_TOTAL2 INT NOT NULL,
    CAMEARA_TOTAL3 INT NOT NULL,
    ACCOUNT_DATE DATE,
    ACCOUNT_DATE_DAY VARCHAR2(10),
    CONSTRAINT FK_ACCOUNTBOOKWRITER FOREIGN KEY (ACCOUNTBOOKWRITER) 
    REFERENCES MEMBER ON DELETE CASCADE
);


--ACCOUNT BOOK DB 끝
 
 select camera_date, sum(camera_total)
 from camera
 group by camera_date
 order by camera_date;
 
 
 